### ISSUE TITLE
Ember data 3.11 docs is broken

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-api-docs#625]
ember data went through some package restructuring as a result of which source code links are broken. This needs to be handled either at this app or at the json api docs generation phase.

**Comment by thomascchen** [comment]
It looks like I can't access Ember Data API docs for any version at the moment.

**Comment by sivakumar-kailasam** [comment]
Thanks for reporting this. An error when viewing the 3.11 docs seems to be causing this behavior.

I've updated this issue to cover this as well.

For anyone facing this, visit https://api.emberjs.com/ember-data/3.10/modules/ember-data & it should work as expected as long as you don't select the 3.11 docs. We'll get this sorted out asap.

**Comment by Gaurav0** [comment]
Was this fixed with the series of Ember Data 3.11 patch releases?

**Comment by sivakumar-kailasam** [comment]
It's partially fixed. We're still working on fixing all aspects of it.

**Comment by sivakumar-kailasam** [comment]
This should be fixed now. Do try a hard reload in case of issues.
